In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("C:/Users/Abhishek Benjamin/Desktop/Download -2/Statistics/Learnbay Data Set/iris.csv")

In [5]:
df.head(3)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa

In [6]:
df.shape

(149, 5)

# Column Renaming

In [8]:
df.rename(columns={'5.1':'sepal-length', '3.5':'sepal-width','1.4': 'petal-length','0.2': 'petal-width',
                     'Iris-setosa':'Class'}, inplace= True)
df.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

# Null Value Check & Missing Value Imputation

In [15]:
df.isnull().sum()

sepal-length    0
sepal-width     0
petal-length    0
petal-width     0
Class           0
dtype: int64

# Bifurcation of Data into Independant & Target Variable

- Independant Variable : X
- Target Variable : Y

In [16]:
 X = df[['sepal-length','sepal-width','petal-length','petal-width']]
 Y = df[['Class']]   

# Standardization of Indepenant Variables

So that it'll make:

- Mean = 0
- Standard Deviation = 1

In [20]:
sc = StandardScaler()

X = sc.fit_transform(X)

X = pd.DataFrame(X)
X.head(3)

0         1         2         3
0 -1.148356 -0.118060 -1.353964 -1.325063
1 -1.390542  0.344859 -1.410986 -1.325063
2 -1.511636  0.113399 -1.296943 -1.325063

# Label Encoding of Target Variable

- To make Machine Learning Algorithm understand Target Variable

In [22]:
encode = LabelEncoder()

Y = encode.fit_transform(Y)
Y = pd.DataFrame(Y)

Y.head()

0
0  0
1  0
2  0
3  0
4  0

# Splitting Data into Train -Test

In [24]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2)

y_train.head()

0
117  2
139  2
124  2
2    0
116  2

# K - Nearest Neighbor Classifier

In [76]:
knn = KNeighborsClassifier(n_neighbors = 5)

knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

# Predictions

In [77]:
y_pred = knn.predict(x_test)

y_pred = pd.DataFrame(y_pred)
y_pred.head()

0
0  2
1  0
2  0
3  0
4  1

# Model Evaluation on Various Paramenters

In [78]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  

In [79]:
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))


[[10  0  0]
 [ 0 13  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.93      0.96        14
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



## Accuracy Score

In [81]:
print(round(accuracy_score(y_test , y_pred)*100,2))

96.67
